title: Natalie Hummel # your name (or website title) here
logo: "/images/roundnatty.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Unicorn 
  <br><br>
  Zombie Preparedness Squad Member 
  <br><br>
  <a href="https://www.linkedin.com/in/nmhummel/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
